# Generated by Django 4.2 on 2024-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_cli', models.CharField(max_length=1)),
                ('nombre_cli', models.CharField(max_length=20)),
                ('ape_pat_cli', models.CharField(max_length=25)),
                ('ape_mat_cli', models.CharField(max_length=25)),
                ('fecha_nac_cli', models.DateField()),
                ('telefono_cli', models.CharField(max_length=15)),
                ('mail_cli', models.EmailField(max_length=254)),
                ('dir_clie', models.CharField(max_length=60)),
                ('pass_cli', models.CharField(max_length=128)),
            ],
        ),
    ]
