# Generated by Django 4.2 on 2024-06-30 18:53

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_rut_cli_alter_cliente_telefono_cli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut_cli',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[clientes.models.validate_only_numbers]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cli',
            field=models.CharField(max_length=15),
        ),
    ]
