# Generated by Django 5.0.6 on 2024-07-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_rut_cli_alter_cliente_telefono_cli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dir_clie',
            new_name='dir_cli',
        ),
    ]
