# Generated by Django 5.0.6 on 2024-07-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_options_cliente_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pass_cli',
        ),
    ]
