# Generated by Django 4.2 on 2024-06-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_cat', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_prod', models.CharField(max_length=50)),
                ('volumen_prod', models.IntegerField()),
                ('desc_prod', models.CharField(max_length=200)),
                ('precio_prod', models.IntegerField()),
                ('stock_prod', models.IntegerField()),
                ('editorial_prod', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_catego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
                ('id_produc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
            options={
                'unique_together': {('id_catego', 'id_produc')},
            },
        ),
    ]
