# Generated by Django 4.2 on 2024-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_prod',
            field=models.CharField(default='General', max_length=15),
        ),
    ]
