ignore:
  paths:
    - media/
  
services:
  - type: web
    plan: free
    name: website-sharingan
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn sharingan.wsgi:application -k uvicorn.workers.UvicornWorker"
