services:
  - type: web
    plan: free
    name: sharingan-website
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn sharingan.wsgi.application -k uvicorn.workers.UvicornWorker"