services:
  - type: web
    plan: free
    name: sharingan-website
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sharingan.sharingan.wsgi:application -k uvicorn.workers.UvicornWorker"

